map $http_x_forwarded_host $proxy_host {
    default $http_x_forwarded_host;
    ""      $host;
}

error_log /dev/stderr;

server {
    listen ${LISTEN_PORT};
    client_max_body_size 0;

    access_log off;

    add_header Access-Control-Allow-Origin *;

    location /play/ {
        alias /tmp/output/;
        types {
            application/vnd.apple.mpegurl m3u8;
            video/mp2t ts;
            video/mp4 m4s mp4;
            text/vtt vtt;
        }
    }

    location / {
        proxy_set_header Host $proxy_host;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        proxy_pass http://unix:/app/rapidbay.sock;
    }

    location /nginx/ {
        internal;
        alias /;
    }
}
