# Type stub for diskcache

from typing import Any, Hashable

class Cache:
    def __init__(self, directory: str) -> None: ...

    def __contains__(self, key: Any) -> bool: ...

    def __getitem__(self, key: Any) -> Any: ...

    def get(self, key: Hashable, default: Any = None) -> Any: ...

    def set(self, key: Hashable, value: Any, expire: int = None) -> bool: ...
